networks:
  plantones-network:
    driver: 'bridge'

services:
  plantones.localhost:
    container_name: plantones.localhost
    build:
      context: .
      dockerfile: ./docker/apache/Dockerfile
    ports:
      - '80:80'
      - '443:443'
    #      - '9000:9000'
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/var/www/html:delegated
      - ./docker/apache/vhost-dev.conf:/etc/apache2/sites-available/000-default.conf:delegated
      - ./docker/apache/vhost-ssl-dev.conf:/etc/apache2/sites-available/default-ssl.conf:delegated
      - ./docker/data/letsencrypt:/etc/letsencrypt
#    environment:
#      PHP_ENABLE_XDEBUG: 1
#      XDEBUG_CONFIG: "client_port=9000 start_with_request=yes idekey=netbeans-xdebug log_level=1 log=/app/xdebug.log discover_client_host=1"
#      XDEBUG_MODE: "develop,debug,coverage"
      #AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      #AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    networks:
      - plantones-network

  mysql.plantones.localhost:
    container_name: mysql.plantones.localhost
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=plantones
      - MYSQL_USER=plantones
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./docker/mysql/my.cnf:/etc/my.cnf
      - mysql_data:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      - plantones-network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  phpmyadmin.plantones.localhost:
    container_name: phpmyadmin.plantones.localhost
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '81:80'
    environment:
      - PMA_HOST=mysql.plantones.localhost
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=
      - PMA_DATABASE=plantones
      - UPLOAD_LIMIT=300M
    networks:
      - plantones-network
    depends_on:
      - mysql.plantones.localhost

volumes:
  mysql_data: